using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class cameraTeletransporte : MonoBehaviour
{
    public destinoCamara.destinos destination;
    public Camera camara;

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player")) // Verifica si el objeto es la c치mara
        {
            // Accede a destinoCamara para obtener la posici칩n de destino
            Vector3 teleportPosition = FindObjectOfType<destinoCamara>().destination[destination];
            // Teletransporta la c치mara a la posici칩n de destino
            camara.transform.position = teleportPosition;
        }
    }
}
